apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
spec:
  rules:
    - host: {{ INGRESS_HOST }}
      http:
        paths:
          - backend:
              service:
                name: foo
                port:
                  name: web
            pathType: Prefix
            path: /
